# Generated by Django 4.2.1 on 2023-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0006_alter_produit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
