# Generated by Django 4.2.1 on 2023-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0012_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=None, upload_to='mercadona/static/mercadona/images/'),
        ),
    ]
