# Generated by Django 4.2.1 on 2023-05-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0013_alter_produit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='descritpion',
            new_name='description',
        ),
    ]
