# Generated by Django 4.2.1 on 2023-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0015_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='durer',
            field=models.DurationField(null=True),
        ),
    ]
