# Generated by Django 4.2.1 on 2023-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0016_produit_durer'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
