# Generated by Django 4.2.1 on 2023-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0017_produit_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.IntegerField(blank=True, null=True)),
                ('durer', models.DurationField(null=True)),
            ],
        ),
    ]
