# Generated by Django 4.2.1 on 2023-05-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0018_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='durer',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='promotion',
        ),
    ]
