# Generated by Django 4.2.1 on 2023-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0019_remove_produit_durer_remove_produit_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
    ]
