# Generated by Django 4.2.1 on 2023-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0020_categorie_remove_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
