# Generated by Django 4.2.1 on 2023-05-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0021_promotion_promo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promo_ID',
        ),
    ]
