# Generated by Django 4.2.1 on 2023-05-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0023_promotion_promo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='promotion',
        ),
    ]
