# Generated by Django 4.2.1 on 2023-05-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0024_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion', models.IntegerField(blank=True, null=True)),
                ('durer', models.DurationField(null=True)),
                ('id_product', models.ForeignKey(default=models.AutoField(primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to='mercadona.produit')),
            ],
        ),
    ]
