# Generated by Django 4.2.1 on 2023-05-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0027_alter_promotion_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='id_product',
        ),
    ]
